examples/db_agent/lib/db_agent.ex, examples/tcp_connection/lib/tcp_connection.ex, integration_test/cases/client_test.exs, integration_test/cases/execute_test.exs, integration_test/cases/query_test.exs, integration_test/cases/run_execute_test.exs, integration_test/cases/transaction_execute_test.exs, lib/db_connection.ex, lib/db_connection/query.ex, test/db_connection_test.exs, test/test_helper.exs
Firstly we provide a mechanism to re-use prepared queries on multiple connections in the same pool. This means that Ecto (or another library) can use its owns global cache of prepared queries with a pool and if a query has not been prepared on the checked out connection it can be prepared and executed.
A naive driver can use this mechanism by trying to execute the query and return `{:prepare, state}` when the database says the query is not prepared. A driver could handle its own cache per connection if it proved beneficial.
Secondly we move query parameters outside of the query term so that it is easier to combine prepared queries and executed parameters.
This means that Ecto (or another library) can do the equivalent of:
```elixir
{pool, opts} = repo.__pool__
case repo.fetch_query(key) …
```
=> Introduce Ecto-style API

integration_test/cases/backoff_test.exs, lib/db_connection.ex, lib/db_connection/backoff.ex, lib/db_connection/connection.ex, mix.exs, mix.lock, test/db_connection/backoff_test.exs, test/test_support.exs
Closes #19.
The backoff API is made slightly clearer (what is `:normal`?), a new backoff type has been added (`:rand`) and there are TODOs to remove backwards compatible code in 1.0.
However perhaps we should move this to Connection as it is likely to be useful there?
=> Remove :backoff dependency

integration_test/ownership/owner_test.exs, lib/db_connection/ownership.ex, lib/db_connection/ownership/owner.ex
Closes #22.
The fix is not quite the same as suggested by #22. We don't want the pool to timeout the connection and disconnect it but the owner process to continue handing out the dead connection with divergent state from the pool. Therefore we pass `timeout: :infinity` to the pool and do a timeout in the owner process. This will allow people to set `ownership_timeout: :infinity` to play with sandboxes in dev/shell.
=> Introduce ownership_timeout

integration_test/cases/close_test.exs, integration_test/cases/execute_test.exs, integration_test/cases/prepare_execute_test.exs, integration_test/cases/prepare_test.exs, integration_test/cases/transaction_test.exs, lib/db_connection.ex, lib/db_connection/log_entry.ex
This adds some major changes in error handling so requires tests plus review. I plan to add a commit which does more error handling in `prepare_execute` (closes prepared query if describe or encode raises).
=> Handle exceptions in Query/Connection callbacks in client process

lib/db_connection/sojourn.ex
I'm not sure it's not a bug this is unused, but I'm not familiar enough with the code to decide.
=> Remove unused module attribute

integration_test/ownership/manager_test.exs, lib/db_connection/ownership.ex, lib/db_connection/ownership/manager.ex
Always use :caller when option is set, and fail if :caller does not have a proxy.
We should release patch to fix this issue. A caller process will get a new proxy in `:auto` mode regardless of `caller` and will get the proxy of `owner` in `{:shared, owner}` even if `caller` is not `owner`.
=> Fix ownership caller to use caller on auto/shared

integration_test/cases/close_test.exs, integration_test/cases/stream_test.exs, integration_test/cases/transaction_test.exs, lib/db_connection.ex
This is  a crucial bug fix as cursors might not be deallocated in some drivers as the deallocation call would raise but the connection would remain open. Also we should be allowing cleanup of prepared queries with `close` once a transaction failed to prevent leaking statements.
This would also help with #82 as deallocate in terminate/2 would always be possible.
=> Allow running cleanup in failed transactions

integration_test/cases/prepare_stream_test.exs, integration_test/cases/stream_test.exs, integration_test/cases/transaction_execute_test.exs, lib/db_connection.ex, lib/db_connection/log_entry.ex
First commit changes the behaviour and the second commit does a substantial refactor to help with #82 and any future metrics work. Hopefully this will pave the way for future integration with any standard instrumentation lib. This PR uses a stateful approach because it fits well with multiple timestampings. However all "connection_time" work is carried out inside a closure except begin/commit/rollback.
=> No longer raise if logging raises

integration_test/cases/transaction_execute_test.exs, integration_test/cases/transaction_test.exs, lib/db_connection.ex, test/test_support.exs
* Add begin(!)/1,2 to checkout and begin
* Add rollback(!)/1,2 to rollback and checkin
* Add commit(!)/1,2 to commit (or rollback) and checkin
rollback/2 is overloaded and has old behaviour inside transaction/3 for
backwards compatibility. However transaction/3 is deprecated because is
makes assumptions about database status that may not hold.
New return values from handle_begin/2, handle_rollback/2 and
handle_commit/2 allow to signal mistaken database status.
=> Introduce begin, rollback and commit

integration_test/cases/cursor_test.exs, integration_test/cases/prepare_stream_test.exs, integration_test/cases/stream_test.exs, integration_test/tests.exs, lib/db_connection.ex, test/test_support.exs
* Add declare(!)/3,4
* Add fetch(!)/3,4
* Add deallocate(!)/3,4
Explicitly defining handle_first/4 and handle_next/4 is deprecated
because callback implementations that are required to differentiate also
need to track cursors in their state. A single fetch/4 is cleaner to use
and these callbacks forward to handle_fetch/4 on `use DBConnection`.
For first/next/fetch the return value is `{:cont | :halt, result, state}`
where `:cont` is continue (same as :ok`) and `:halt` means both that the
cursor has finished enumerating results and the cursor is deallocated.
Therefore `:halt` does not require a `deallocate` call. This API is
chosen to avoid an extra roundtrip that current adapters do.
handle_first/4 and handle_next/4 still support `:ok` and `:deallocate`
tuples.
A callback implementation …
=> Introduce declare/fetch/deallocate

integration_test/cases/transaction_test.exs, lib/db_connection.ex, test/test_support.exs
* Add status/2
Returns `:idle | :transaction | :error` and does not raise. Change
handle_begin/rollback/commit returns to match status and deprecate
their error exception tuples. Disconnect should always be used
there.
=> Introduce status/2

integration_test/cases/execute_test.exs, lib/db_connection.ex, test/test_support.exs
This change will allow us to cast parameters if the parameter types have changed when executing a query that has not been prepared on a connection, decode using the new result types. This will allow us more chances not to error in Ecto when a migration occurs live.
=> Allow execute to prepare new query

lib/db_connection.ex
Getting errors when testing out mssqlex with updated version of DBConnection because of this.
According to docs this default should still be here.
=> adding default empty options for a transaction

integration_test/ownership/manager_test.exs, lib/db_connection/ownership/manager.ex
This fixes a bug where processes started before the ownership
mode is set to shared holds on to the previous connection,
causing confusion.
See #96
=> Checkin previous connections when setting ownership mode to shared

integration_test/cases/cursor_test.exs, integration_test/cases/stream_test.exs, lib/db_connection.ex
Follow up to #91 to allow the same feature for streams/cursor. This will allow us to use prepared queries in Ecto for streams.
=> Allow declare to prepare new query

integration_test/cases/idle_test.exs, integration_test/cases/queue_test.exs, integration_test/connection_pool/all_test.exs, integration_test/connection_pool/test_helper.exs, lib/db_connection/app.ex, lib/db_connection/connection.ex, lib/db_connection/connection_pool.ex, lib/db_connection/connection_pool/pool.ex, lib/db_connection/connection_pool/pool_supervisor.ex, mix.exs
Adds a built in connection pool that will increase throughput by 3-7% for most single queries and load levels in Ecto. Other workloads may get 0%-10% improvements. 
The pool uses an ETS queue and some other ETS trickier to avoid tracking busy connections/clients. The later feature (if this was only pool style) would allow us to stop using the pdict so that we can ensure no data leaks for non-closure transactions.
We might be able to get better performance by removing either or both of these ETS use cases.
IO overload handling is better (and simpler) than Sojourn pool. In future we could improve the case where the database is down or other side of netsplit because we can know when there are no connections.
CPU overload handling is not as good as Sojourn pool but could be improved by …
=> Add built in connection pool

integration_test/cases/prepare_stream_test.exs, integration_test/cases/stream_test.exs, lib/db_connection.ex, lib/db_connection/connection.ex, test/db_connection_test.exs, test/test_support.exs
This commit also moves the handling of replies to each callback
instead of a main `handle` function as otherwise we would need
to push `function_exported?/3` concerns into it.
=> Use optional_callbacks instead of relying on default implementations

lib/db_connection.ex
=> queue config doc fix: milliseconds, not micro

lib/db_connection.ex
See https://github.com/elixir-ecto/myxql/pull/41/files for how it can be used. When this is merged, I'll perform similar changes in Postgrex.
Latest versions on Hex are db_connection 2.0.5 and postgrex 0.14.1. Say we release these types on 2.0.6 and 0.14.2, respectively. If users update to Postgrex 0.14.2 but keeps db_connection < 2.0.6, they will get a Dialyzer error:
Unknown type: DBConnection.start_option/0
We could bump Postgrex's dependency requirement but that seems too much? Perhaps having this comment here should be enough to unblock folks if they run into it.
=> Add start_option/0 and option/0 types

integration_test/cases/queue_test.exs, lib/db_connection/connection_pool.ex, lib/db_connection/holder.ex
It was possible for a deadline timeout to arrive at the connection pool and for the deadline to be current in the holder but the client to checkin the connection holder before the pool deleted the holder for disconnect. This leads to an `ETS-TRANSFER` message with the deleted holder being handled by the pool and added to the queue. Therefore we check holders exist before checking in, and crash if we get in a inconsistent due to a future bug.
=> Fix race condition where we checkin a connection after timeout

lib/db_connection.ex, lib/db_connection/connection.ex, lib/db_connection/ownership/proxy.ex
I'm adding `crash_reason` on use of `Logger.error` so that projects using libraries like `sentry-elixir` will be able to capture these logged messages.
=> Logger with crash_reason metadata

CHANGELOG.md, integration_test/cases/idle_test.exs, lib/db_connection.ex, lib/db_connection/connection_pool.ex, lib/db_connection/connection_pool/pool.ex, mix.exs, test/db_connection_test.exs, test/test_support.exs
One possible downside of this approach is that
we may shut down all connections at once and if
there is a request around this time, the response
time will be higher. However, this is likely better
than the current approach, where we ping only the
first one, which means we can have a pool of stale
connections. Ideally we would introduce some sort
of jitter, to ensure we don't disconnect all of
them immediately, but this can be in the future.
The current behaviour is the same as in v1.0.
=> Ping all stale connections on idle interval

.github/workflows/ci.yml, lib/db_connection.ex, lib/db_connection/connection.ex, lib/db_connection/holder.ex, mix.exs
Replace deprecated `System.stacktrace()` by `__STACKTRACE__` to fix warnings in Elixir 1.11.
Bumped minimal elixir version accordingly to 1.7 (like ecto's [current release](https://github.com/elixir-ecto/ecto/blob/v3.4.6/mix.exs#L10))
=> Replace deprecated stacktraces and bump requirements

integration_test/cases/connection_listeners_test.exs, integration_test/tests.exs, lib/db_connection.ex, lib/db_connection/connection.ex
The `:connection_listeners` option allows one or more processes to be notified whenever a connection is connected or disconnected. A listener may be a remote or local PID, a local port, a locally registered name, or a tuple in the form of `{registered_name, node}` for a registered name at another node.
Each listener process may receive the following messages where `pid` identifies the connection process:
* `{:connected, pid}`
* `{:disconnected, pid}`
Related to #227.
@josevalim Does this follow what you were initally suggesting?
=> Add `:connection_listeners` option to `DBConnection.start_link/2`

CHANGELOG.md, integration_test/cases/connection_listeners_test.exs
Add a longer back-off minimum value to the connection listeners tests to allow for slower test execution.
Fixes failing CI tests in #228 when run for older Elixir and Erlang versions.
=> Fix failing connection listeners test

integration_test/cases/queue_test.exs, integration_test/connection_pool/test_helper.exs, integration_test/ownership/test_helper.exs, lib/db_connection.ex, lib/db_connection/holder.ex, mix.exs, mix.lock
As discussed in #235 and #234, this PR adds a telemetry event for `DBConnection.ConnectionError`s.
There are some discussion points still:
1. Which `opts` should we add to `metadata`?
2. Is there any meaningful measurement we could add instead of `%{error: 1}`?
3. Although the tests pass as expected, when I used this code in a local project (pointing to the local path for `db_connection`), the `:connection_listeners` option is empty. Is this expected? This was the only way I could think of for monitoring a project with different `Ecto.Repo`s. Or maybe this event should be published by either `postgrex`, or `ecto_sql` or even `ecto`?
I chose to keep publishing the event basically in the same place as in #235 because the `opts` could be useful in handling multiple-Ecto.Repo projects.
=> feat: add telemetry event for queue timeouts

lib/db_connection/connection_pool.ex
I ran into this error while running tests on a different project and noticed the awkward `albeit it` which I don't think is correct.
I changed it to `although this` which is a bit simpler, but could otherwise be `albeit increasing resource consumption`.
WDYT?
=> Improve grammar in error message

lib/db_connection.ex, lib/db_connection/connection_pool.ex
This way we can reference it in the docs without an ExDoc warning. (Postgrex already did that which triggered this change.) Just adding a very basic `@moduledoc`, all its functions are still hidden.
=> Document `DBConnection.ConnectionPool`

integration_test/connection_pool/disconnect_all_test.exs, integration_test/ownership/disconnect_all_test.exs, lib/db_connection/holder.ex
Because `disconnect_all` is being explicitly called, the logging message doesn't need to be as verbose as it is. This changes the severity to debug. From @josevalim's [comment here](https://github.com/elixir-ecto/db_connection/issues/99#issuecomment-1058472198).
=> Change disconnect_all log severity to debug

lib/db_connection.ex
Hi!
As usual, thank you for the work in this repo! I noticed we didn't have a small example implementation for a `connection_listener`. After playing around with some code, I arrived at the the one below think it may serve as a nice starting point for folks wanting to implement their own `connection_listeners`.
The simplest way I found to test/prove it worked was to add it to a test, I do it [here](https://github.com/pdgonzalez872/db_connection/commit/845c2aaf8be97c7e1b65e335a4c73f13e74478f9)
Hope this helps!
=> Add example implementation for a connection_listener

.formatter.exs, integration_test/cases/after_connect_test.exs, integration_test/cases/client_test.exs, integration_test/cases/close_test.exs, integration_test/cases/connect_test.exs, integration_test/cases/connection_listeners_test.exs, integration_test/cases/execute_test.exs, integration_test/cases/idle_test.exs, integration_test/cases/prepare_execute_test.exs, integration_test/cases/prepare_stream_test.exs, integration_test/cases/prepare_test.exs, integration_test/cases/queue_test.exs, integration_test/cases/stream_test.exs, integration_test/cases/transaction_execute_test.exs, integration_test/cases/transaction_test.exs, integration_test/connection_pool/all_test.exs, integration_test/connection_pool/disconnect_all_test.exs, integration_test/ownership/all_test.exs, integration_test/ownership/manager_test.exs, integration_test/ownership/owner_test.exs, integration_test/ownership/test_helper.exs, integration_test/tests.exs
I’m not sure if it was intentional or not, but the rest of the library is formatted, so I figured this would make sense.
=> Format the integration_test directory

lib/db_connection.ex
`idle_interval` option was repeated in sentence. Should be `idle_interval` and `idle_limit`.
=> Small doc fix on ping callback

lib/db_connection.ex, test/db_connection_test.exs
This would be awesome in [Xandra](https://github.com/lexhide/xandra) for example, because we could split start options in
1. Xandra options, which we validate
2. DBConnection options, which we pass down to DBConnection
3. Any other option, for which we'd raise as "unknown option"
If this is a good addition, I can do the same for `t:DBConnection.option/0`.
=> Add DBConnection.available_start_options/0

integration_test/cases/transaction_test.exs, lib/db_connection.ex, test/test_support.exs
Closes https://github.com/elixir-ecto/db_connection/issues/296
=> Allow handle_begin to return query

lib/db_connection.ex
Closes https://github.com/elixir-ecto/db_connection/issues/302
=> Document `:pool_index`

lib/db_connection/connection.ex, lib/db_connection/connection_error.ex
I also moved the connection error definition into its own file and added some guards to its `exception/2` function.
The idea here is to lay the foundations for expanding `:reason` so that programmers can gather more from that instead of sometimes having to match on the message.
=> Add DBConnection.ConnectionError.t/0 type

lib/db_connection.ex, lib/db_connection/connection.ex
Found via `typos --hidden --format brief`
=> Fix typos again

integration_test/cases/connection_listeners_test.exs, lib/db_connection.ex, lib/db_connection/telemetry_listener.ex
Alternative to #310. Would have to write documentation, etc.
=> Add a connection listener that emits telemetry events

lib/db_connection.ex, lib/db_connection/ownership.ex
=> Use `is_pid` and improve doc

.formatter.exs, examples/tcp_connection/lib/tcp_connection.ex, integration_test/cases/info_test.exs, integration_test/connection_pool/disconnect_all_test.exs, lib/db_connection/connection.ex, test/test_support.exs
Context: https://github.com/elixir-ecto/db_connection/issues/315#issuecomment-2467547996
=> Proxy info messages to the adapter
