elixir-ecto/db_connection

integration_test/cases/after_connect_test.exs, integration_test/cases/backoff_test.exs, integration_test/tests.exs, lib/db_connection.ex, lib/db_connection/app.ex, lib/db_connection/connection.ex, lib/db_connection/task.ex, mix.exs
=> Introduce after_connect option

integration_test/sojourn/shutdown_test.exs, integration_test/sojourn/test_helper.exs, lib/db_connection/app.ex, lib/db_connection/sojourn.ex, lib/db_connection/sojourn/broker.ex, lib/db_connection/sojourn/pool.ex, lib/db_connection/sojourn/starter.ex, lib/db_connection/sojourn/supervisor.ex, lib/db_connection/sojourn/watcher.ex
=> Return broker pid from sojourn's start_link

lib/db_connection.ex
=> Fix typo in lib/db_connection.ex

lib/db_connection/ownership/manager.ex
I think this will be a great help to track down ownership issues. Closes #50.
=> Log ownership changes

lib/db_connection.ex
=> Update docs and default opts to []

lib/db_connection/ownership.ex
=> Add :caller to ownership error message

integration_test/ownership/shutdown_test.exs, integration_test/sojourn/shutdown_test.exs, lib/db_connection/app.ex, lib/db_connection/ownership/pool.ex, lib/db_connection/ownership/pool_supervisor.ex, lib/db_connection/sojourn/pool.ex, lib/db_connection/sojourn/supervisor.ex, lib/db_connection/watcher.ex
@fishcakez I am not quite sure how to solve this for sbroker. It seems it has an init callback but it doesn't have a terminate one?
=> Cleanly shutdown ownership and sojourn pools (#94)

integration_test/cases/transaction_test.exs, lib/db_connection.ex
Disconnect when transaction function returns unexpected status unless a commit can be turned into rollback.
The worst situation here is that a begin returns that the connection status is `:transaction` and we used to return it to the pool. Therefore the connection would get stuck in transaction status.
=> Disconnect when can't handle unexpected transaction status

integration_test/ownership/manager_test.exs, lib/db_connection/ownership/manager.ex
Closes #110.
Back port to v1.1 branch on merge.
=> Support checkout/allow on auto/shared via caller option

examples/db_agent/mix.exs, examples/tcp_connection/lib/tcp_connection.ex, examples/tcp_connection/mix.exs
`to_char_list/1` has been deprecated
=> Minor upgrade to /examples

integration_test/cases/transaction_execute_test.exs, integration_test/cases/transaction_test.exs, lib/db_connection.ex, test/test_support.exs
We can add it back later but for now YAGNI.
=> Remove begin/rollback/commit explicit API

examples/tcp_connection/lib/tcp_connection.ex, integration_test/cases/connect_test.exs, lib/db_connection.ex, lib/db_connection/connection.ex, test/test_support.exs
=> Remove handle_info callback

integration_test/cases/after_connect_test.exs, integration_test/cases/client_test.exs, integration_test/cases/connect_test.exs, integration_test/cases/idle_test.exs, integration_test/cases/queue_test.exs, integration_test/cases/transaction_test.exs, integration_test/connection_pool/test_helper.exs, integration_test/ownership/manager_test.exs, integration_test/ownership/owner_test.exs, integration_test/ownership/test_helper.exs, lib/db_connection.ex, test/test_support.exs
=> Check the status on DBConnection.run

integration_test/cases/client_test.exs, integration_test/cases/stream_test.exs, integration_test/cases/transaction_execute_test.exs, integration_test/ownership/owner_test.exs, lib/db_connection.ex, lib/db_connection/connection.ex, lib/db_connection/connection_pool.ex, lib/db_connection/holder.ex, lib/db_connection/ownership.ex, lib/db_connection/ownership/proxy.ex, lib/db_connection/task.ex
@fishcakez, please review.
I have dropped comments on the relevant bits. Also please review the changes on holder, task and connection.
=> Remove the process dictionary

integration_test/cases/client_test.exs, integration_test/cases/stream_test.exs, integration_test/cases/transaction_execute_test.exs, lib/db_connection/holder.ex
=> Improve errors on connection closed

lib/db_connection/ownership/proxy.ex
I was able to verify the logs appear twice in the DBConnection suite. However, once I remove those log calls, [this Ecto test no longer passes](https://github.com/elixir-ecto/ecto/blob/a17bf6089b539c45d8681054766b532f63e0a36d/integration_test/sql/sandbox.exs#L144) as nothing is logged. Thoughts @fishcakez?
=> Remove duplicate proxy logs

lib/db_connection/connection.ex, lib/db_connection/holder.ex
=> Cleanly shut connection down when there is no pool in update

integration_test/cases/client_test.exs, lib/db_connection/holder.ex
=> Lock connection and pool

lib/db_connection/connection.ex, lib/db_connection/connection_pool.ex
=> Add process info stacktrace, if available, to logged message

lib/db_connection.ex
I found this sentence that didn't quite make sense in the docs. I fixed according to what I think was meant by it, might still be wrong.
=> Improve broken sentence

lib/db_connection.ex, lib/db_connection/query.ex
=> Improve docs around DBConnection.Query

integration_test/cases/idle_test.exs, integration_test/ownership/test_helper.exs, lib/db_connection.ex, lib/db_connection/connection_pool.ex, lib/db_connection/holder.ex, lib/db_connection/log_entry.ex, lib/db_connection/ownership.ex, lib/db_connection/ownership/proxy.ex, lib/db_connection/task.ex
=> Add idle_time to LogEntry

.travis.yml
Please refer to https://github.com/dashbitco/broadway/pull/188 for justification.
=> add more recent Elixir and Erlang/OTP combinations to CI

.formatter.exs, lib/db_connection.ex, lib/db_connection/app.ex, lib/db_connection/backoff.ex, lib/db_connection/connection.ex, lib/db_connection/connection_pool.ex, lib/db_connection/ownership.ex, lib/db_connection/ownership/manager.ex, lib/db_connection/ownership/proxy.ex, lib/db_connection/query.ex, lib/db_connection/task.ex, lib/db_connection/watcher.ex, test/db_connection/backoff_test.exs, test/test_helper.exs, test/test_support.exs
Since the minimum Elixir version is 1.7+, we should mix format the
the whole module.
=> Mix format

lib/db_connection.ex, test/db_connection_test.exs
=> Add support for connection reference in DBConnection.connection_module/1

integration_test/cases/connect_test.exs, integration_test/ownership/manager_test.exs, lib/db_connection/connection.ex, mix.exs, mix.lock
Just started on this but all tests pass 🙃 I also tried this branch out in ecto_sql and all tests pass there too. I'll see if I can try it in Postgrex maybe.
=> Replace Connection with gen_statem

lib/db_connection.ex, lib/db_connection/connection_pool.ex, lib/db_connection/ownership.ex, lib/db_connection/pool.ex
We can keep this private for now, but I think it would be nice to have it internally and possibly expose it one day?
=> Add DBConnection.Pool behaviour

lib/db_connection.ex, test/db_connection_test.exs
=> Add DBConnection.available_connection_options/0

integration_test/cases/connection_listeners_test.exs, lib/db_connection.ex, lib/db_connection/connection.ex, test/db_connection_test.exs
=> Add :connection_listeners_tag
